import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;
import java.text.SimpleDateFormat;

public class MarketGUI {
    private JPanel MainPanel;
    private JPanel NorthPanel;
    private JPanel SouthPanel;
    private JPanel CenterPanel;
    private JComboBox StockCombo;
    private JComboBox StartMonthCombo;
    private JComboBox StartDayCombo;
    private JComboBox StartYearCombo;
    private JComboBox EndMonthCombo;
    private JComboBox EndDayCombo;
    private JComboBox EndYearCombo;
    private JButton seeThisStockButton;

    public MarketGUI() {
        seeThisStockButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object source = e.getSource();
                if (source == seeThisStockButton) {
                    Object objStock = StockCombo.getSelectedItem();
                    Object objSM = StartMonthCombo.getSelectedItem();
                    Object objSY = StartYearCombo.getSelectedItem();
                    Object objSD = StartDayCombo.getSelectedItem();
                    Object objEM = StartMonthCombo.getSelectedItem();
                    Object objEY = StartYearCombo.getSelectedItem();
                    Object objED = StartDayCombo.getSelectedItem();
                    if (objStock != null && objSM != null && objSY != null && objSD != null
                            && objEM != null && objEY != null && objED != null) {
                        String choStock = objStock.toString();
                        String choStartDate = objSM.toString() + "/" + objSD.toString() + "/" + objSY.toString();
                        String choEndDate = objEM.toString() + "/" + objED.toString() + "/" + objEY.toString();
                        SimpleDateFormat sdf = new SimpleDateFormat( " MM/dd/yyyy" );
                        String today = sdf.format(new Date());
                        if (choStartDate > ){

                        }
                        else{
                            System.out.println("Please select stock, start date and end date.");
                        }
                    }
                    else{
                        System.out.println("Please select stock, start date and end date.");
                    }
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MarketGUI");
        frame.setContentPane(new MarketGUI().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        NorthPanel = new JPanel();
        NorthPanel.setLayout(new GridBagLayout());
        MainPanel.add(NorthPanel, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Best Stock Market APP of 2018");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        NorthPanel.add(label1, gbc);
        SouthPanel = new JPanel();
        SouthPanel.setLayout(new GridBagLayout());
        MainPanel.add(SouthPanel, BorderLayout.SOUTH);
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        SouthPanel.add(label2, gbc);
        CenterPanel = new JPanel();
        CenterPanel.setLayout(new GridBagLayout());
        MainPanel.add(CenterPanel, BorderLayout.CENTER);
        StockCombo = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("APPL");
        defaultComboBoxModel1.addElement("FB");
        defaultComboBoxModel1.addElement("GOOG");
        defaultComboBoxModel1.addElement("YHOO");
        StockCombo.setModel(defaultComboBoxModel1);
        StockCombo.setSelectedIndex(-1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        CenterPanel.add(StockCombo, gbc);
        StartMonthCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 0, 0);
        CenterPanel.add(StartMonthCombo, gbc);
        StartDayCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        CenterPanel.add(StartDayCombo, gbc);
        StartYearCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        CenterPanel.add(StartYearCombo, gbc);
        EndMonthCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 0, 0);
        CenterPanel.add(EndMonthCombo, gbc);
        EndDayCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 0, 0);
        CenterPanel.add(EndDayCombo, gbc);
        EndYearCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 0, 0);
        CenterPanel.add(EndYearCombo, gbc);
        seeThisStockButton = new JButton();
        seeThisStockButton.setText("See this stock !");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 0);
        CenterPanel.add(seeThisStockButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Find a Stock !");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        CenterPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Start Date :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 0, 5);
        CenterPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("End Date :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 0, 5);
        CenterPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Month");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        CenterPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Day");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        CenterPanel.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Year");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        CenterPanel.add(label8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
