import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.text.SimpleDateFormat;

public class MarketGUI {
    private JPanel MainPanel;
    private JPanel NorthPanel;
    private MessagePanel mPanel;
    private CenterPanel cPanel;
    private JComboBox StockCombo;
    private JComboBox StartMonthCombo;
    private JComboBox StartDayCombo;
    private JComboBox StartYearCombo;
    private JComboBox EndMonthCombo;
    private JComboBox EndDayCombo;
    private JComboBox EndYearCombo;
    private JButton GoButton;

    public MarketGUI() {

        /**
        * Add ActionListener to GoButton, to check whether the dates are legal. If not, print error on MessagePanel.
        * */
        GoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object source = e.getSource();
                if (source == GoButton) {
                    Object objStock = StockCombo.getSelectedItem();
                    Object objSM = StartMonthCombo.getSelectedItem();
                    Object objSY = StartYearCombo.getSelectedItem();
                    Object objSD = StartDayCombo.getSelectedItem();
                    Object objEM = EndMonthCombo.getSelectedItem();
                    Object objEY = EndYearCombo.getSelectedItem();
                    Object objED = EndDayCombo.getSelectedItem();
                    if (objStock != null && objSM != null && objSY != null && objSD != null
                            && objEM != null && objEY != null && objED != null) {
                        String choStock = objStock.toString();
                        String choStartDate = objSM.toString() + "/" + objSD.toString() + "/" + objSY.toString();
                        String choEndDate = objEM.toString() + "/" + objED.toString() + "/" + objEY.toString();
                        try {
                            Date start = new SimpleDateFormat("MM/dd/yyyy").parse(choStartDate);
                            Date end = new SimpleDateFormat("MM/dd/yyyy").parse(choEndDate);
                            Date today = new Date();
                            if (end.after(today)) { //Error1
                                mPanel.setDisplayString("End Date Error: later than today.");
                            } else if (start.after(end)) { // Error2
                                mPanel.setDisplayString("Start Date Error: later than End Date.");
                            } else { //OK
                                DataRetriever dr = new DataRetriever(choStock, choStartDate, choEndDate);
                                //ArrayList<Object> Stock = dr.getStock();
                            }
                        } catch (Exception ex) {
                            ex.printStackTrace(System.err);
                        }
                    } else { //Error3
                        mPanel.setDisplayString("Please select stock, start date and end date.");
                    }
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MarketGUI");
        frame.setContentPane(new MarketGUI().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        //frame.setResizable(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        setupUI();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void setupUI() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridBagLayout());
        MainPanel.setForeground(new Color(-12828863));
        GridBagConstraints MainGBC=new GridBagConstraints();

        //North
        NorthPanel = new JPanel();
        NorthPanel.setLayout(new GridBagLayout());
        MainGBC.gridx=0;
        MainGBC.gridy=0;
        MainGBC.weightx=1;
        MainGBC.weighty=1;
        MainGBC.fill=GridBagConstraints.BOTH;
        MainPanel.add(NorthPanel, MainGBC);
        final JLabel label1 = new JLabel();
        label1.setText("Sheng Liang");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        NorthPanel.add(label1, gbc);

        //South
        mPanel = new MessagePanel();
        MainGBC.gridx=0;
        MainGBC.gridy=2;
        MainGBC.weightx=1;
        MainGBC.weighty=1;
        MainGBC.fill=GridBagConstraints.BOTH;
        mPanel.setDisplayString("Welcome to MarketGUI !");
        MainPanel.add(mPanel, MainGBC);
        mPanel.setPreferredSize(new Dimension(100, 40));

        //Center
        cPanel= new CenterPanel();
        MainGBC.gridx=0;
        MainGBC.gridy=1;
        MainGBC.weightx=1;
        MainGBC.weighty=10;
        MainGBC.fill=GridBagConstraints.BOTH;
        MainPanel.add(cPanel, MainGBC);
        gbc = cPanel.getGbc();
        GoButton = cPanel.getGoButton();
        StartMonthCombo = cPanel.getStartMonthCombo();
        StartDayCombo = cPanel.getStartDayCombo();
        StartYearCombo = cPanel.getStartYearCombo();
        EndMonthCombo = cPanel.getEndMonthCombo();
        EndDayCombo = cPanel.getEndDayCombo();
        EndYearCombo = cPanel.getEndYearCombo();
        StockCombo = cPanel.getStockCombo();
    }

    /**
     * @noinspection ALL
     */
    private Font getFont(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent getRootComponent() {
        return MainPanel;
    }

}
